container_name := "cuda_test"
default_container_cmd := "./f.out"

make:
	make bin/c.out

run: make
	./bin/c.out

build-container:
	podman build -t {{ container_name }} .

run-container cmd=default_container_cmd: build-container
	podman run --rm --device=nvidia.com/gpu=all {{ container_name }} {{ cmd }}
