src := "./main.f90"
out := "./main.out"

# Test program
test: format build
    {{ out }} --help

# Build program
build:
    gfortran {{ src }} -o {{ out }}

# Format code
format:
    fprettify {{ src }}
