#import "template.typ": conf

#let abstract = [
  Isotropic turbulence generated by dragon's fire breath
  is a captivating phenomenon that has intrigued researchers for centuries.
  In this study,
  we delve into the intriguing world of mythical creatures by investigating
  the energy spectra of two distinct dragon species
  --- wyverns and traditional dragons ---
  shedding light on their unique characteristics and underlying mechanisms.
  Utilizing advanced mathematical formulations,
  we aim to shed light on the underlying physics
  and gain insights into the unique properties of their turbulent fire flows.
]

#show: doc => conf(
  title: "
    Feeding the Flame: Exploring the Mysteries of
    Isotropic Turbulence from Dragon's Fire
  ",
  authors: (
    (
      name: "Loïc Reynier",
      affiliation: "Medmora Drake University",
      email: "loic.reynier@drake.edu",
    ),
  ),
  abstract: abstract,
  doc,
)

= Introduction

Within the realms where dragons soar the skies and breathe fire,
the awe-inspiring spectacle of their fiery breath
has inspired legends and inspired scientific curiosity for generations.
Isotropic turbulence,
the mesmerizing fluid behavior characterized by energy cascades across scales,
is at the heart of this phenomenon.
This study ventures into the magical world of dragons to examine
the isotropic turbulence in the fire breath of
wyverns and traditional dragons,
providing unprecedented insights through the formulation of energy spectra

= Methodology

To explore the mysteries of dragon fire breath,
a harmonious collaboration between dragon scholars
and human researchers is fostered.
Wyverns and traditional dragons, hailing from diverse regions,
are closely observed in their natural habitats.
Advanced magical imaging techniques,
augmented with human technology,
capture the turbulent dynamics of their fire breath.
Incorporating the essence of dragon magic,
we derive formulae for the energy spectra of their fiery exhalations.

= Energy Spectra Formulations

In the realm of wyverns,
their fire energy spectrum,
denoted $E_upright(W)$,
is expressed by the mystical formula
$ E_upright(W)(k) = A_upright(W) k^(-5/3) exp(-k/k_0), $ <wyvern_spectra>
where
$k$ is the wavenumber representing the scale of turbulence,
$A_upright(W)$ is a dragon-specific constant
and $k_0$ is the characteric wavenumber indicating the peak energy scale.

For traditional dragons, their fire energy spectrum,
denoted as $E_upright(D)(k)$,
embodies a more intricate nature and is represented by the enchanted formula
$ E_upright(D)(k)
  = A_upright(D) k^(-5/3) + B_upright(D) k^(-2) exp(-k/k_0),
$ <dragon_spectra>
where
- $A_upright(D)$ is a unique constant tied to the dragon's ancient lineage,
- $B_upright(D)$ represents the influence of rare dragon traits,
- $k_0$ retains its significance as the characteristic wavenumber.

= Data Collection and Analysis

Magical energy measurements,
facilitated by the harmonious blend of dragon magic and human instrumentation,
are collected during dragons' fire-breathing events.
The collected data undergo meticulous spectral analysis
using state-of-the-art methods involving dragon-enchanted
Fourier Transform techniques.

= Results

The spectral analyses of wyverns' and traditional dragons' fire breath
reveal captivating distinctions.
Wyverns' fire exhibits a well-defined
inertial subrange in the energy spectrum,
consistent with the classical $-5/3$ power-law scaling predicted
by Kolmogorov turbulence theory.
In contrast,
traditional dragons' fire unveils a fascinating dual-cascade behavior,
characterized by $-5/3$ scaling at large scales
and $-2$ scaling at small scales.
This unique dual-cascade phenomenon suggests an intriguing interplay
of elemental forces and mythical intricacies.

= Discussion

The distinct energy spectra observed
in wyverns' and traditional dragons' fire breath
lead us to contemplate the underlying magical processes
governing their fiery abilities.
Variations in dragon physiology,
elemental composition,
and ancient lineage are proposed
as factors influencing the energy transfer mechanisms,
giving rise to the contrasting turbulence behaviors.

= Conclusion

By formulating energy spectra for
wyverns' and traditional dragons' fire breath,
this study provides a deeper understanding of the isotropic turbulence
at play in their awe-inspiring abilities.
The enchanting discoveries made in this study transcend
the boundaries of the magical realm
and hold profound implications for scientific understanding.
The formulation of energy spectra
and the revelation of dual-cascade behaviors
can inspire advancements in fluid dynamics, combustion science,
and energy generation research.
Moreover, this exploration of isotropic turbulence in dragon fire breath may
spark novel applications in sustainable energy harnessing
and environmental studies.
The harmonious alliance between dragon magic and human science offers
a unique gateway to exploring
the enigmatic dynamics of these mythical creatures,
enriching both realms with newfound wisdom and wonder.

// vim: ft=text
